require("config.lazy")
require("config.postLoadConfig")
require("config.colorVerticalBar")
require("config.personalThemeConfig")
-- ********* color themes  use <leader>uC ***********
--vim.cmd("colorscheme solarized-osaka")
--vim.cmd("colorscheme gruvbox")
-- vim.cmd("colorscheme github_light_default")
--vim.cmd("colorscheme dayfox")
--vim.cmd("colorscheme everforest")
--vim.cmd("colorscheme catppuccin-latte")
--vim.cmd("colorscheme blue")
--vim.cmd("colorscheme lackluster")
--vim.cmd("colorscheme tokyonight")
---------------------------------------
--ConfigMyColor()
