# ================================
# Configuración de Alacritty
# ================================

[font]
normal = { family = "DejaVu Sans Mono", style = "Regular" }
bold = { family = "DejaVu Sans Mono", style = "Bold" }
italic = { family = "DejaVu Sans Mono", style = "Italic" }
bold_italic = { family = "DejaVu Sans Mono", style = "Bold Italic" }
#
# normal = { family = "AnonymicePro Nerd Font Mono", style = "Regular" }
# bold = { family = "AnonymicePro Nerd Font Mono", style = "Bold" }
# italic = { family = "AnonymicePro Nerd Font Mono", style = "Italic" }
# bold_italic = { family = "AnonymicePro Nerd Font Mono", style = "Bold Italic" }
#
# normal = { family = "Cascadia Code PL", style = "Regular" }
# bold = { family = "Cascadia Code PL", style = "Bold" }
# italic = { family = "Cascadia Code PL", style = "Italic" }
# bold_italic = { family = "Cascadia Code PL", style = "Bold Italic" }
#
# normal = { family = "monospace", style = "Regular" }
# bold = { family = "monospace", style = "Bold" }
# italic = { family = "monospace", style = "Italic" }
# bold_italic = { family = "monospace", style = "Bold Italic" }
#
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
# italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
# bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
#
size = 11.0                     # Un poco más grande que 11 para legibilidad
offset = { x = 0, y = 1 }       # Ajuste vertical fino
glyph_offset = { x = 0, y = 0 }

# ================================
# Colores
# ================================
[colors.primary]
# Catppuccin base (puedes mantener el import también al final)
background = "#001419"
foreground = "#cdd6f4"

[colors.cursor]
text = "#001419"
cursor = "#cdd6f4"

# Retro opcional (descomenta uno para probar)
# Verde fósforo
# background = "#000000"
# foreground = "#33FF33"
# cursor = { text = "#000000", cursor = "#33FF33" }

# Ámbar fósforo
# background = "#000000"
# foreground = "#FFB000"
# cursor = { text = "#000000", cursor = "#FFB000" }

# ================================
# Ventana
# ================================
[window]
opacity = 0.95               # Un toque de transparencia
padding = { x = 10, y = 10 } # Margen interno
blur = true                  # Si tu compositor soporta (ej. picom)

# ================================
# Terminal
# ================================
[terminal.shell]
program = "/usr/bin/tmux"

# ================================
# Scrollback
# ================================
[scrolling]
history = 10000
multiplier = 3

# ================================
# Atajos de teclado
# ================================
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

# ================================
# Tema externo
# ================================
[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-frappe.toml"]
